version: '2'

services:
 v2ray:
    image: alliswell2day/v2:go
    restart: always
    network_mode: "host"
    environment:
      sspanel_url: "https://xxxx"
      key: "Alliswell2day1477"
      docker: "true"
      speedtest: 6
      node_id: 10
      api_port: 4444
    logging:
      options:
        max-size: "10m"
        max-file: "3"

 caddy:
    image: alliswell2day/v2:caddy
    restart: always
    environment:
      - ACME_AGREE=true
#      if u want to use cloudflare (for DNS challenge authentication)
#      - CLOUDFLARE_EMAIL=xxxxxx@out.look.com
#      - CLOUDFLARE_API_KEY=xxxxxxx
      - V2RAY_DOMAIN=xxxx.com
      - V2RAY_PATH=/v2ray
      - V2RAY_EMAIL=xxxx@outlook.com
      - V2RAY_PORT=4445
      - V2RAY_OUTSIDE_PORT=443
    network_mode: "host"
    volumes:
      - ./.caddy:/root/.caddy
      - ./Caddyfile:/etc/Caddyfile
